#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""TradePulse Anti-Pattern Checker.

Static checks for the MANDATORY CONSTRAINTS in
``docs/development_standards_compressed.md``. Designed to be run by the
F3 regression gate (``docs/workflow_guide.md``) and pre-commit hooks.

Checks (each maps to a documented constraint):
  1. bare-except        — ``except:`` with no exception type.
  2. session-local      — ``SessionLocal()`` used outside scripts/tests.
  3. db-pattern-mix     — ``get_db()`` with ``await session.execute`` OR
                          ``get_async_db()`` with ``session.query(`` (runtime errors).
  4. naive-datetime     — ``datetime.now()`` / ``datetime.utcnow()`` (use timezone_utils).
  5. aioredis-import    — ``import aioredis`` (use ``redis.asyncio as aioredis``).
  6. module-global-svc  — module-level ``name = SomeClient()`` service instantiation.
  7. relative-import    — ``from .x import`` / ``from ..x import`` (absolute only).
  8. try-except-import  — ``try: import ...  except ImportError`` workaround.

Severity:
  ERROR  → violates a MANDATORY constraint; exits non-zero (blocks).
  WARN   → likely issue but context-dependent; reported, does not block
           unless ``--strict``.

Usage (from ``backend_v4/`` project root):
    python scripts/check_anti_patterns.py                # scan app/ + scripts/ + tradepulse_core/
    python scripts/check_anti_patterns.py --changed-only # only git-changed *.py (fast, for hooks)
    python scripts/check_anti_patterns.py --paths app/learning app/services
    python scripts/check_anti_patterns.py --strict       # treat warnings as failures
    python scripts/check_anti_patterns.py --json         # machine-readable output

Design notes
------------
- Uses Python's ``ast`` where structure matters (bare except, module-level
  instantiation, relative imports, try/except-ImportError) — far fewer false
  positives than regex. Falls back to line regex only for textual patterns.
- Conservative by default: the notoriously noisy "magic number" check from the
  standards sketch is intentionally OMITTED here (it produced thousands of false
  positives). Magic numbers remain a code-review item, not an automated blocker.
- Scans default roots ``app``, ``scripts``, ``tradepulse_core`` excluding
  ``tests``, ``__pycache__``, ``venv``, ``alembic/versions`` (migrations
  legitimately use literals + are autogenerated).
"""
from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, List, Optional


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ROOTS = ("app", "scripts", "tradepulse_core")
EXCLUDED_DIR_PARTS = {
    "__pycache__", ".git", "venv", ".venv", "node_modules",
    "tests", "test", ".pytest_cache", "scratch", "tmp",
}
# Migrations are autogenerated and legitimately contain literals / raw SQL.
EXCLUDED_PATH_SUBSTR = ("alembic/versions", "alembic\\versions")

# SessionLocal() is allowed in these directory names (per standards).
SESSION_LOCAL_ALLOWED_DIRS = {"scripts", "tests"}
# Files where SessionLocal()/sessionmaker legitimately lives (the factory itself
# defines and calls it — flagging these would be a false positive).
SESSION_LOCAL_ALLOWED_FILES = {"database.py", "database_optimizer.py"}

SEVERITY_ERROR = "ERROR"
SEVERITY_WARN = "WARN"


@dataclass
class Finding:
    path: str
    line: int
    check: str
    severity: str
    message: str

    def format(self) -> str:
        return f"  [{self.severity}] {self.check} {self.path}:{self.line}  {self.message}"


@dataclass
class CheckResult:
    findings: List[Finding] = field(default_factory=list)

    def add(self, *args, **kwargs) -> None:
        self.findings.append(Finding(*args, **kwargs))

    @property
    def errors(self) -> List[Finding]:
        return [f for f in self.findings if f.severity == SEVERITY_ERROR]

    @property
    def warnings(self) -> List[Finding]:
        return [f for f in self.findings if f.severity == SEVERITY_WARN]


# ── File discovery ────────────────────────────────────────────────────

def _is_excluded(path: Path) -> bool:
    parts = set(path.parts)
    if parts & EXCLUDED_DIR_PARTS:
        return True
    # The checker file legitimately contains the very tokens it detects (in its
    # docstring + regex pattern literals); never scan itself.
    if path.name == "check_anti_patterns.py":
        return True
    p = path.as_posix()
    return any(sub in p for sub in EXCLUDED_PATH_SUBSTR)


def discover_files(roots: Iterable[str]) -> List[Path]:
    files: List[Path] = []
    for root in roots:
        root_path = (PROJECT_ROOT / root) if not Path(root).is_absolute() else Path(root)
        if root_path.is_file() and root_path.suffix == ".py":
            if not _is_excluded(root_path):
                files.append(root_path)
            continue
        if not root_path.exists():
            continue
        for f in root_path.rglob("*.py"):
            if not _is_excluded(f):
                files.append(f)
    return sorted(set(files))


def discover_changed_files() -> List[Path]:
    """Return git-changed *.py files (staged + unstaged + untracked)."""
    try:
        out = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=PROJECT_ROOT, capture_output=True, text=True, check=True,
        ).stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []
    files: List[Path] = []
    for line in out.splitlines():
        # porcelain format: "XY <path>" (path starts at col 3)
        raw = line[3:].strip()
        if " -> " in raw:  # renamed
            raw = raw.split(" -> ", 1)[1]
        if not raw.endswith(".py"):
            continue
        p = PROJECT_ROOT / raw
        if p.exists() and not _is_excluded(p):
            files.append(p)
    return sorted(set(files))


# ── AST-based checks ──────────────────────────────────────────────────

class _AstVisitor(ast.NodeVisitor):
    def __init__(self, path: str, source: str, result: CheckResult):
        self.path = path
        self.source = source
        self.result = result

    # Bare except (ERROR)
    def visit_ExceptHandler(self, node: ast.ExceptHandler) -> None:
        if node.type is None:
            self.result.add(
                self.path, node.lineno, "bare-except", SEVERITY_ERROR,
                "bare 'except:' — catch a specific exception (or 'except Exception')",
            )
        self.generic_visit(node)

    # Relative imports (ERROR) + try/except ImportError workaround handled separately
    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        if node.level and node.level > 0:
            self.result.add(
                self.path, node.lineno, "relative-import", SEVERITY_ERROR,
                f"relative import (level={node.level}) — use absolute 'app.*' imports",
            )
        self.generic_visit(node)

    # Module-level service instantiation: ``name = SomeClient()`` at module scope.
    def visit_Module(self, node: ast.Module) -> None:
        for stmt in node.body:
            if isinstance(stmt, ast.Assign):
                self._check_module_assign(stmt)
        self.generic_visit(node)

    def _check_module_assign(self, stmt: ast.Assign) -> None:
        # value must be a direct Call to a Name/Attribute that looks like a class
        if not isinstance(stmt.value, ast.Call):
            return
        func = stmt.value.func
        callee = None
        if isinstance(func, ast.Name):
            callee = func.id
        elif isinstance(func, ast.Attribute):
            callee = func.attr
        if not callee:
            return
        # Heuristic: class-like CamelCase name. Exclude obvious non-services by
        # requiring a service/singleton-ish suffix (see _RE_SERVICE_HINT).
        if not callee[:1].isupper():
            return
        if not _RE_SERVICE_HINT.search(callee):
            return
        # Only flag when assigned to a module-level lowercase name (a de-facto global singleton).
        targets = [t for t in stmt.targets if isinstance(t, ast.Name)]
        for t in targets:
            if t.id[:1].islower() and not t.id.startswith("_"):
                self.result.add(
                    self.path, stmt.lineno, "module-global-svc", SEVERITY_WARN,
                    f"module-level '{t.id} = {callee}()' — use a lazy get_*() factory",
                )


def _find_try_except_import(tree: ast.AST, path: str, result: CheckResult) -> None:
    """Flag ``try: import X  except ImportError`` workarounds (WARN).

    Excludes the legitimate optional-dependency pattern where the handler does
    NOT rebind the name to a stub (hard to tell statically), so this is a WARN.
    """
    for node in ast.walk(tree):
        if not isinstance(node, ast.Try):
            continue
        body_is_import = node.body and all(
            isinstance(s, (ast.Import, ast.ImportFrom)) for s in node.body
        )
        if not body_is_import:
            continue
        for handler in node.handlers:
            names = []
            h = handler.type
            if isinstance(h, ast.Name):
                names = [h.id]
            elif isinstance(h, ast.Tuple):
                names = [e.id for e in h.elts if isinstance(e, ast.Name)]
            if "ImportError" in names or "ModuleNotFoundError" in names:
                result.add(
                    path, node.lineno, "try-except-import", SEVERITY_WARN,
                    "try/except ImportError around import — prefer a lazy import "
                    "inside the method (see standards: Lazy Imports)",
                )
                break


# ── Line/regex-based checks ───────────────────────────────────────────

_RE_NAIVE_NOW = re.compile(r"\bdatetime\.(now|utcnow)\s*\(")
_RE_NOW_WITH_TZ = re.compile(r"datetime\.now\s*\(\s*[^)]*tz")  # datetime.now(tz=...) is OK
_RE_AIOREDIS = re.compile(r"^\s*import\s+aioredis\b")
_RE_SESSION_LOCAL = re.compile(r"\bSessionLocal\s*\(")
_RE_GET_DB_AWAIT = re.compile(r"get_async_db\b")  # presence marker for async ctx
_RE_AWAIT_EXECUTE = re.compile(r"await\s+\w+\.execute\s*\(")
_RE_SESSION_QUERY = re.compile(r"\b\w+\.query\s*\(")
# Module-level service/singleton class-name suffixes for module-global-svc check.
# Compiled once (not per _check_module_assign call).
_RE_SERVICE_HINT = re.compile(
    r"(Client|Service|Manager|Engine|Orchestrator|Tracker|"
    r"Scheduler|Collector|Poller|Detector|Calculator|Aggregator)$"
)


def _check_lines(path: Path, source: str, result: CheckResult) -> None:
    rel = _rel(path)
    lines = source.splitlines()

    # Per-file DB context detection for the mix check.
    # Require the CALL form ``get_db(`` / ``get_async_db(`` (not a bare mention in
    # a docstring or regex literal) to avoid false positives on files that merely
    # describe these patterns (e.g. this checker itself).
    calls_get_db = bool(re.search(r"\bget_db\s*\(", source)) and not re.search(r"\bget_async_db\s*\(", source)
    calls_async_db = bool(re.search(r"\bget_async_db\s*\(", source))

    for i, line in enumerate(lines, 1):
        stripped = line.strip()
        if stripped.startswith("#"):
            continue

        # naive datetime
        if _RE_NAIVE_NOW.search(line) and not _RE_NOW_WITH_TZ.search(line):
            # allow inside timezone_utils.py itself (it defines now_utc/now_local)
            if path.name != "timezone_utils.py":
                result.add(
                    rel, i, "naive-datetime", SEVERITY_ERROR,
                    "datetime.now()/utcnow() — use app.core.timezone_utils.now_utc/now_local",
                )

        # aioredis
        if _RE_AIOREDIS.match(line):
            result.add(
                rel, i, "aioredis-import", SEVERITY_ERROR,
                "import aioredis — use 'import redis.asyncio as aioredis'",
            )

        # SessionLocal() outside allowed dirs
        if _RE_SESSION_LOCAL.search(line):
            if not (set(path.parts) & SESSION_LOCAL_ALLOWED_DIRS) \
                    and path.name not in SESSION_LOCAL_ALLOWED_FILES:
                result.add(
                    rel, i, "session-local", SEVERITY_ERROR,
                    "SessionLocal() outside scripts/tests — use get_db()/get_async_db()",
                )

    # DB pattern mix (file-level heuristic)
    if calls_get_db and _RE_AWAIT_EXECUTE.search(source):
        # find a representative line
        ln = _first_match_line(lines, _RE_AWAIT_EXECUTE)
        result.add(
            rel, ln, "db-pattern-mix", SEVERITY_WARN,
            "file uses get_db() (sync) but has 'await session.execute(' — "
            "verify it isn't mixing sync get_db() with async execute",
        )
    if calls_async_db and _RE_SESSION_QUERY.search(source):
        ln = _first_match_line(lines, _RE_SESSION_QUERY)
        result.add(
            rel, ln, "db-pattern-mix", SEVERITY_WARN,
            "file uses get_async_db() but has 'session.query(' — "
            "AsyncSession has no .query(); use await session.execute(select(...))",
        )


def _first_match_line(lines: List[str], pattern: re.Pattern) -> int:
    for i, line in enumerate(lines, 1):
        if pattern.search(line):
            return i
    return 1


# ── Orchestration ─────────────────────────────────────────────────────

def _rel(path: Path) -> str:
    try:
        return path.relative_to(PROJECT_ROOT).as_posix()
    except ValueError:
        return str(path)


def check_file(path: Path, result: CheckResult) -> None:
    try:
        source = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        result.add(_rel(path), 0, "read-error", SEVERITY_WARN, f"could not read: {exc}")
        return

    # AST checks (skip files that don't parse — report as WARN, don't crash)
    try:
        tree = ast.parse(source, filename=str(path))
        visitor = _AstVisitor(_rel(path), source, result)
        visitor.visit(tree)
        _find_try_except_import(tree, _rel(path), result)
    except SyntaxError as exc:
        result.add(_rel(path), exc.lineno or 0, "syntax-error", SEVERITY_WARN,
                   f"AST parse failed: {exc.msg}")

    # Line/regex checks
    _check_lines(path, source, result)


def run(paths: List[Path], strict: bool, as_json: bool) -> int:
    result = CheckResult()
    for p in paths:
        check_file(p, result)

    if as_json:
        payload = {
            "files_scanned": len(paths),
            "errors": len(result.errors),
            "warnings": len(result.warnings),
            "findings": [f.__dict__ for f in result.findings],
        }
        print(json.dumps(payload, indent=2))
    else:
        if result.errors:
            print("[FAIL] Anti-pattern ERRORS (block):\n")
            for f in result.errors:
                print(f.format())
        if result.warnings:
            print("\n[WARN] Anti-pattern WARNINGS (review):\n")
            for f in result.warnings:
                print(f.format())
        print(
            f"\nScanned {len(paths)} file(s): "
            f"{len(result.errors)} error(s), {len(result.warnings)} warning(s)."
        )
        if not result.findings:
            print("[OK] No anti-patterns detected.")

    # Exit code: errors always fail; warnings fail only under --strict.
    if result.errors:
        return 1
    if strict and result.warnings:
        return 1
    return 0


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="check_anti_patterns.py",
        description="TradePulse anti-pattern checker (development_standards_compressed.md).",
    )
    parser.add_argument(
        "--paths", nargs="*", default=None,
        help=f"Paths to scan (default: {' '.join(DEFAULT_ROOTS)}).",
    )
    parser.add_argument(
        "--changed-only", action="store_true",
        help="Scan only git-changed *.py files (fast; for pre-commit hooks).",
    )
    parser.add_argument(
        "--strict", action="store_true",
        help="Treat warnings as failures (non-zero exit).",
    )
    parser.add_argument(
        "--json", action="store_true", dest="as_json",
        help="Emit machine-readable JSON.",
    )
    args = parser.parse_args(argv)

    if args.changed_only:
        files = discover_changed_files()
        if not files:
            if not args.as_json:
                print("[OK] No changed Python files to scan.")
            return 0
    else:
        roots = args.paths if args.paths else list(DEFAULT_ROOTS)
        files = discover_files(roots)

    return run(files, strict=args.strict, as_json=args.as_json)


if __name__ == "__main__":
    sys.exit(main())
